// <copyright file="GenerateDriveShortcuts.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace SystemTrayMenu.Utilities
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Runtime.InteropServices;

    internal class GenerateDriveShortcuts
    {
        public static void Start()
        {
            List<char> driveNamesToRemove = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToCharArray().ToList();

            DriveInfo[] driveInfos = DriveInfo.GetDrives();
            foreach (DriveInfo driveInfo in driveInfos)
            {
                driveNamesToRemove.Remove(driveInfo.Name[0]);
                string linkPath = GetLinkPathFromDriveName(driveInfo.Name[..1]);
                if (!System.IO.File.Exists(linkPath))
                {
                    CreateShortcut(linkPath, driveInfo.Name);
                }
            }

            foreach (char driveName in driveNamesToRemove)
            {
                string possibleShortcut = GetLinkPathFromDriveName(driveName.ToString());

                try
                {
                    System.IO.File.Delete(possibleShortcut);
                }
                catch (Exception ex)
                {
                    Log.Warn($"Could not delete shortcut at path:'{possibleShortcut}'", ex);
                }
            }
        }

        private static void CreateShortcut(string linkPath, string targetPath)
        {
            try
            {
                Type? shellType = Type.GetTypeFromProgID("WScript.Shell");
                if (shellType == null)
                {
                    Log.Info("CreateShortcut WScript.Shell COM type not found");
                    return;
                }

                object shell = Activator.CreateInstance(shellType)!;
                object? shortcut = shellType.InvokeMember(
                    "CreateShortcut",
                    BindingFlags.InvokeMethod,
                    binder: null,
                    target: shell,
                    args: new object[] { linkPath });
                if (shortcut == null)
                {
                    Log.Info($"CreateShortcut returned null for path:'{linkPath}'");
                    return;
                }

                Type shortcutType = shortcut.GetType();
                _ = shortcutType.InvokeMember(
                    "Description",
                    BindingFlags.SetProperty,
                    binder: null,
                    target: shortcut,
                    args: new object[] { "Generated by SystemTrayMenu" });
                _ = shortcutType.InvokeMember(
                    "TargetPath",
                    BindingFlags.SetProperty,
                    binder: null,
                    target: shortcut,
                    args: new object[] { targetPath });
                _ = shortcutType.InvokeMember(
                    "Save",
                    BindingFlags.InvokeMethod,
                    binder: null,
                    target: shortcut,
                    args: null);

                if (Marshal.IsComObject(shortcut))
                {
                    _ = Marshal.FinalReleaseComObject(shortcut);
                }

                if (Marshal.IsComObject(shell))
                {
                    _ = Marshal.FinalReleaseComObject(shell);
                }
            }
            catch (Exception ex)
            {
                Log.Warn($"Could not create shortcut at path:'{linkPath}'", ex);
            }
        }

        private static string GetLinkPathFromDriveName(string driveName)
        {
            return Path.Combine(Config.Path, $" {driveName}       .lnk");
        }
    }
}
